<?php

namespace Database\Seeders;

use App\Models\AlmanacEntry;
use Illuminate\Database\Seeder;

/**
 * The Academic Almanac 2026/2027, as consolidated by the Office of the
 * Academic Registrar (draft for Senate review, 26 July 2026).
 *
 * Transcribed from the Registrar's document rather than invented. Two classes
 * of source problem were handled explicitly rather than silently:
 *
 *  · Year typos inside a month section (the April 2027 table carries "3/5/6
 *    April 2026" for Easter and "8 April 2026" for a Faculty Board; January
 *    2027 carries "6 January 2026"). These are normalised to the year of the
 *    section they sit in, which is the same treatment the source document's
 *    own "Editorial normalisations applied" table describes. NOTE: the Easter
 *    *dates* themselves are 2026's dates — in 2027 Good Friday falls in March
 *    — so those three rows are flagged for confirmation, not quietly moved.
 *  · Entries the source leaves undated ("TBC", "Ongoing throughout the
 *    academic year") keep no start date and group under "Ongoing", so they
 *    can never masquerade as belonging to a month.
 *
 * The internal draft-control matter of the document — the confirmation
 * register, the editorial-normalisation table and the abbreviation list — is
 * deliberately not seeded as calendar entries: it is Senate review apparatus,
 * not the academic year. The abbreviations are rendered as a reference block
 * on the almanac page itself.
 */
class AlmanacSeeder extends Seeder
{
    private const YEAR = '2026/2027';

    public function run(): void
    {
        AlmanacEntry::query()->delete();

        $order = 0;
        foreach ($this->entries() as $row) {
            AlmanacEntry::create([
                'academic_year' => self::YEAR,
                'semester' => $row['semester'],
                'period' => $row['period'],
                'starts_on' => $row['starts'] ?? null,
                'ends_on' => $row['ends'] ?? null,
                'activity' => $row['activity'],
                'responsible' => $row['who'] ?? null,
                'category' => $row['cat'] ?? null,
                'is_key_date' => $row['key'] ?? false,
                'sort_order' => ++$order,
            ]);
        }
    }

    /** @return list<array<string,mixed>> */
    private function entries(): array
    {
        $s1 = 'Semester I';
        $s2 = 'Semester II';
        $rec = 'Recess & Internship';
        $on = 'Ongoing';

        return [
            // ---------------------------------------------- Pre-opening 2026
            ['semester' => $s1, 'period' => '2 July 2026', 'starts' => '2026-07-02',
                'activity' => 'University Budget meeting', 'who' => 'University Bursar', 'cat' => 'governance'],
            ['semester' => $s1, 'period' => '20 July – 1 August 2026', 'starts' => '2026-07-20', 'ends' => '2026-08-01',
                'activity' => 'Semester I sports trials', 'who' => 'Sports Tutor', 'cat' => 'student'],
            ['semester' => $s1, 'period' => '22 July 2026', 'starts' => '2026-07-22',
                'activity' => 'Admissions Committee of Senate', 'who' => 'Academic Registrar', 'cat' => 'governance'],
            ['semester' => $s1, 'period' => '3 August 2026', 'starts' => '2026-08-03',
                'activity' => 'Commencement of Academic Year 2026/2027, welcoming of fresh students and commencement of lectures',
                'who' => 'Academic Registrar / Deans / All lecturers', 'cat' => 'academic', 'key' => true],
            ['semester' => $s1, 'period' => '3 – 6 August 2026', 'starts' => '2026-08-03', 'ends' => '2026-08-06',
                'activity' => 'Orientation Week for freshers — arrival, hall and hostel allocation and registration',
                'who' => 'MANCO / Academic staff / Dean of Students / Warden', 'cat' => 'student', 'key' => true],

            // ---------------------------------------------------- August 2026
            ['semester' => $s1, 'period' => 'Week 2, August 2026', 'starts' => '2026-08-10',
                'activity' => 'Orientation of student leaders', 'who' => 'Dean of Students', 'cat' => 'student'],
            ['semester' => $s1, 'period' => '7 August 2026', 'starts' => '2026-08-07',
                'activity' => 'Faculty Board meetings (beginning of semester) — FSSAH and FSTEAD',
                'who' => 'Faculty Deans', 'cat' => 'academic'],
            ['semester' => $s1, 'period' => '10 August 2026', 'starts' => '2026-08-10',
                'activity' => 'Beginning of semester for weekend graduate students; commencement of Semester I lectures (Years I, II & III); Academic and Quality Assurance Committee (Council Q1)',
                'who' => 'Academic staff / Graduate Centre / Governing Council Secretariat', 'cat' => 'academic'],
            ['semester' => $s1, 'period' => '11 August 2026', 'starts' => '2026-08-11',
                'activity' => 'Resource Mobilisation Committee (Council Q1)', 'who' => 'Governing Council Secretariat', 'cat' => 'governance'],
            ['semester' => $s1, 'period' => '12 August 2026', 'starts' => '2026-08-12',
                'activity' => 'Research, Ethics, Publications and Quality Assurance Committee; Audit and Risk Management Committee (Council Q1)',
                'who' => 'CGC / Deans / QA / Governing Council Secretariat', 'cat' => 'governance'],
            ['semester' => $s1, 'period' => '13 August 2026', 'starts' => '2026-08-13',
                'activity' => "Students' Affairs Committee (Council Q1)", 'who' => 'Governing Council Secretariat', 'cat' => 'governance'],
            ['semester' => $s1, 'period' => '14 August 2026', 'starts' => '2026-08-14',
                'activity' => 'Finance and Planning Committee (Council Q1)', 'who' => 'Governing Council Secretariat', 'cat' => 'governance'],
            ['semester' => $s1, 'period' => 'Week 3, August 2026', 'starts' => '2026-08-17',
                'activity' => 'Health and wellness awareness week', 'who' => 'Dean of Students', 'cat' => 'student'],
            ['semester' => $s1, 'period' => '16 August – 6 September 2026', 'starts' => '2026-08-16', 'ends' => '2026-09-06',
                'activity' => 'Sports friendlies', 'who' => 'Sports Tutor', 'cat' => 'student'],
            ['semester' => $s1, 'period' => '17 August 2026', 'starts' => '2026-08-17',
                'activity' => 'Appointments and Governance Committee (Council Q1); welcoming of all Faculty students',
                'who' => 'Governing Council Secretariat / FSTEAD', 'cat' => 'governance'],
            ['semester' => $s1, 'period' => '18 August 2026', 'starts' => '2026-08-18',
                'activity' => '51st Senate meeting; Faculty of Education departmental meeting; Projects Committee (Council Q1)',
                'who' => 'Academic Registrar / Dean, FoE / Governing Council Secretariat', 'cat' => 'governance'],
            ['semester' => $s1, 'period' => '19 August 2026', 'starts' => '2026-08-19',
                'activity' => 'Ceremonies Committee of Senate (08:00); Business Committee (Council Q1)',
                'who' => 'Academic Registrar / Governing Council Secretariat', 'cat' => 'governance'],
            ['semester' => $s1, 'period' => '20 August 2026', 'starts' => '2026-08-20',
                'activity' => 'Teaching and Learning Committee (09:00); submission of Graduate School thesis; digital pedagogy and ICT training',
                'who' => 'Quality Assurance / Graduate Centre / Dean, FBM / ICT Unit', 'cat' => 'academic'],
            ['semester' => $s1, 'period' => '21 August 2026', 'starts' => '2026-08-21',
                'activity' => 'Appointments and Governance Committee; first Guild Representative Council sitting',
                'who' => 'Council Secretariat / Dean of Students / Guild President', 'cat' => 'governance'],
            ['semester' => $s1, 'period' => '24 August 2026', 'starts' => '2026-08-24',
                'activity' => 'Commencement of general August in-service session; Graduate Board of Senate meeting; August Research Seminar',
                'who' => 'Dean, FoE / Manager, In-service / DVC / Graduate Centre', 'cat' => 'academic'],
            ['semester' => $s1, 'period' => '24 August – 12 September 2026', 'starts' => '2026-08-24', 'ends' => '2026-09-12',
                'activity' => 'Faculty of Education / MEMA August in-service session',
                'who' => 'FoE / Manager, In-service / Graduate Centre', 'cat' => 'academic'],
            ['semester' => $s1, 'period' => '25 August 2026', 'starts' => '2026-08-25',
                'activity' => 'Faculty of Education Board meeting', 'who' => 'Faculty Dean', 'cat' => 'academic'],
            ['semester' => $s1, 'period' => '26 – 30 August 2026', 'starts' => '2026-08-26', 'ends' => '2026-08-30',
                'activity' => 'Faculty Board meetings; Programs Committee of Senate',
                'who' => 'Deans of Faculties / Academic Registrar', 'cat' => 'academic'],
            ['semester' => $s1, 'period' => '27 August 2026', 'starts' => '2026-08-27',
                'activity' => 'International Day and cultural week activities', 'who' => 'Academic Registrar & International Office', 'cat' => 'student'],
            ['semester' => $s1, 'period' => '28 August 2026', 'starts' => '2026-08-28',
                'activity' => 'Student hostel and hall meeting; games team registration; Governing Council 1st Quarterly Meeting',
                'who' => 'Warden / Sports Tutor / Governing Council Secretariat', 'cat' => 'governance'],
            ['semester' => $s1, 'period' => '29 August 2026', 'starts' => '2026-08-29',
                'activity' => 'Grants, Projects and Innovations Committee; Teaching and Learning Committee',
                'who' => 'CGC / Faculty Deans / Manager, Quality Assurance', 'cat' => 'governance'],
            ['semester' => $s1, 'period' => '31 August – 6 September 2026', 'starts' => '2026-08-31', 'ends' => '2026-09-06',
                'activity' => 'Resource Mobilisation and Marketing (09:00)', 'who' => 'Governing Council Secretariat', 'cat' => 'governance'],

            // ------------------------------------------------- September 2026
            ['semester' => $s1, 'period' => '1 September 2026', 'starts' => '2026-09-01',
                'activity' => 'Admissions Committee of Senate (09:00); Estate and Facilities Management (11:30); career guidance and school visits',
                'who' => 'Academic Registrar / DVC & Estates Officer / Marketing Officer', 'cat' => 'governance'],
            ['semester' => $s1, 'period' => '2 September 2026', 'starts' => '2026-09-02',
                'activity' => 'MRU inter-association debate; Extended MANCO meeting', 'who' => 'Association Patrons', 'cat' => 'student'],
            ['semester' => $s1, 'period' => '3 September 2026', 'starts' => '2026-09-03',
                'activity' => 'Admissions Committee of Senate', 'who' => 'Academic Registrar', 'cat' => 'governance'],
            ['semester' => $s1, 'period' => '4 September 2026', 'starts' => '2026-09-04',
                'activity' => 'Procurement Committee meeting', 'who' => 'Dr P. Bwowe', 'cat' => 'governance'],
            ['semester' => $s1, 'period' => '5 September 2026', 'starts' => '2026-09-05',
                'activity' => 'Research proposal defence (graduate students)', 'who' => 'Co-ordinator & all academic staff', 'cat' => 'research'],
            ['semester' => $s1, 'period' => '7 September 2026', 'starts' => '2026-09-07',
                'activity' => 'First assignment week; Graduate research concept defence',
                'who' => 'Deans / All academic staff / Graduate Centre', 'cat' => 'academic'],
            ['semester' => $s1, 'period' => '7 – 13 September 2026', 'starts' => '2026-09-07', 'ends' => '2026-09-13',
                'activity' => 'First set of Semester I tests', 'who' => 'Deans / HoDs / Academic Registrar', 'cat' => 'examination', 'key' => true],
            ['semester' => $s1, 'period' => '8 – 10 September 2026', 'starts' => '2026-09-08', 'ends' => '2026-09-10',
                'activity' => 'ODEL system training, Kakeeka Campus', 'who' => 'MIS', 'cat' => 'academic'],
            ['semester' => $s1, 'period' => '11 September 2026', 'starts' => '2026-09-11',
                'activity' => 'Human Resource induction and staff training workshop; Freshers\' Ball; end of general August in-service session',
                'who' => 'HR Officer / Dean of Students / Guild President / FoE', 'cat' => 'student'],
            ['semester' => $s1, 'period' => '12 September 2026', 'starts' => '2026-09-12',
                'activity' => 'End of MEMA in-service August session', 'who' => 'FoE / Graduate Centre', 'cat' => 'academic'],
            ['semester' => $s1, 'period' => '14 September 2026', 'starts' => '2026-09-14',
                'activity' => 'Faculty Board meeting — FSTEAD', 'who' => 'Faculty Dean', 'cat' => 'academic'],
            ['semester' => $s1, 'period' => '15 – 17 September 2026', 'starts' => '2026-09-15', 'ends' => '2026-09-17',
                'activity' => 'ODEL system training, Kirumba Campus', 'who' => 'MIS / FBM / Quality Assurance Unit', 'cat' => 'academic'],
            ['semester' => $s1, 'period' => '16 September 2026', 'starts' => '2026-09-16',
                'activity' => 'Quality assurance in higher education workshop', 'who' => 'Quality Assurance Unit', 'cat' => 'academic'],
            ['semester' => $s1, 'period' => '17 September 2026', 'starts' => '2026-09-17',
                'activity' => 'Integrating Competence-Based Education and Training (CBET) into existing university systems',
                'who' => 'Academic Registrar / Quality Assurance Unit', 'cat' => 'academic'],
            ['semester' => $s1, 'period' => '18 September 2026', 'starts' => '2026-09-18',
                'activity' => 'Faculty of Business and Management Semester I student orientation (09:00); Deans\' Forum (14:00)',
                'who' => 'Dean, FBM / Student Associations / DVC', 'cat' => 'academic'],
            ['semester' => $s1, 'period' => '18 – 20 September 2026', 'starts' => '2026-09-18', 'ends' => '2026-09-20',
                'activity' => 'Visit of the Katikkiro to Toro Sub-Region', 'who' => 'Marketing Officer', 'cat' => 'outreach'],
            ['semester' => $s1, 'period' => '19 – 21 September 2026', 'starts' => '2026-09-19', 'ends' => '2026-09-21',
                'activity' => 'Hostel and halls inspection', 'who' => 'Warden', 'cat' => 'student'],
            ['semester' => $s1, 'period' => '19 September 2026', 'starts' => '2026-09-19',
                'activity' => 'Faculty of Education community engagement activity', 'who' => 'Dean, FoE / Heads of Department', 'cat' => 'outreach'],
            ['semester' => $s1, 'period' => '22 – 27 September 2026', 'starts' => '2026-09-22', 'ends' => '2026-09-27',
                'activity' => 'CBS PEWOSA agri-business fair', 'who' => 'Marketing Officer', 'cat' => 'outreach'],
            ['semester' => $s1, 'period' => '23 September 2026', 'starts' => '2026-09-23',
                'activity' => '35th Examinations Board meeting for Summer School examinations',
                'who' => 'DVC / Examinations Coordinator', 'cat' => 'examination'],
            ['semester' => $s1, 'period' => '24 September 2026', 'starts' => '2026-09-24',
                'activity' => 'Ceremonies Committee of Senate (09:00); Teaching and Learning Committee (14:00)',
                'who' => 'Academic Registrar / Manager, Quality Assurance', 'cat' => 'governance'],
            ['semester' => $s1, 'period' => '25 September 2026', 'starts' => '2026-09-25',
                'activity' => 'Examinations Irregularities / Disciplinary Committee — Kakeeka; AUUS Annual General Meeting; data analysis basics (SPSS, Excel and AI)',
                'who' => 'DVC / Examinations Coordinator / Dean of Students / FBM Research and Training Committee', 'cat' => 'examination'],
            ['semester' => $s1, 'period' => '26 September 2026', 'starts' => '2026-09-26',
                'activity' => '52nd Senate meeting; Faculty of Education research publication training',
                'who' => 'Academic Registrar / Dean, FoE / Research Committee', 'cat' => 'governance'],
            ['semester' => $s1, 'period' => '28 September 2026', 'starts' => '2026-09-28',
                'activity' => 'September Research Seminar; community engagement — visit to schools',
                'who' => 'Graduate Centre / FSTEAD', 'cat' => 'research'],
            ['semester' => $s1, 'period' => '28 – 30 September 2026', 'starts' => '2026-09-28', 'ends' => '2026-09-30',
                'activity' => 'Counselling and mental health campaign', 'who' => 'Counsellor', 'cat' => 'student'],
            ['semester' => $s1, 'period' => '30 September 2026', 'starts' => '2026-09-30',
                'activity' => 'Examinations Irregularities / Disciplinary Committee — Kirumba',
                'who' => 'DVC / Examinations Coordinator', 'cat' => 'examination'],

            // --------------------------------------------------- October 2026
            ['semester' => $s1, 'period' => '3 October 2026', 'starts' => '2026-10-03',
                'activity' => 'Appointments and Governance Committee (Q2)', 'who' => 'Council Secretariat', 'cat' => 'governance'],
            ['semester' => $s1, 'period' => '5 October 2026', 'starts' => '2026-10-05',
                'activity' => 'Last day for setting examination papers and marking schemes', 'who' => 'All academic staff', 'cat' => 'examination'],
            ['semester' => $s1, 'period' => '5 – 10 October 2026', 'starts' => '2026-10-05', 'ends' => '2026-10-10',
                'activity' => 'Tourism & Hotel Management academic field trip', 'who' => 'HoD, Tourism & Hotel Management', 'cat' => 'academic'],
            ['semester' => $s1, 'period' => '6 October 2026', 'starts' => '2026-10-06',
                'activity' => 'Grants, Projects and Innovations Committee; Extended MANCO meeting', 'who' => 'Graduate Centre', 'cat' => 'governance'],
            ['semester' => $s1, 'period' => '7 October 2026', 'starts' => '2026-10-07',
                'activity' => 'Audit and Risk Management Committee (Q2)', 'who' => 'Council Secretariat', 'cat' => 'governance'],
            ['semester' => $s1, 'period' => '9 October 2026', 'starts' => '2026-10-09',
                'activity' => 'Public Holiday: Independence Day', 'who' => 'All staff and students to note', 'cat' => 'holiday'],
            ['semester' => $s1, 'period' => '12 – 13 October 2026', 'starts' => '2026-10-12', 'ends' => '2026-10-13',
                'activity' => 'Research progress review and presentation — FSSAH', 'who' => 'Dean & all academics', 'cat' => 'research'],
            ['semester' => $s1, 'period' => '13 October 2026', 'starts' => '2026-10-13',
                'activity' => 'Faculty of Education departmental meeting; Academic and Quality Assurance Committee (Q2)',
                'who' => 'Dean, FoE / Heads of Department / Council Secretariat', 'cat' => 'governance'],
            ['semester' => $s1, 'period' => '14 – 18 October 2026', 'starts' => '2026-10-14', 'ends' => '2026-10-18',
                'activity' => 'Moderation of examinations', 'who' => 'Deans / Heads of Department', 'cat' => 'examination'],
            ['semester' => $s1, 'period' => '15 October 2026', 'starts' => '2026-10-15',
                'activity' => 'Student leadership workshop (08:00); Research, Ethics, Publications and Quality Assurance Committee (14:00)',
                'who' => 'Dean of Students / CGC / Deans / Faculty Representatives', 'cat' => 'student'],
            ['semester' => $s1, 'period' => '16 October 2026', 'starts' => '2026-10-16',
                'activity' => 'Display of Semester I examination timetable', 'who' => 'Deans / Heads of Department', 'cat' => 'examination', 'key' => true],
            ['semester' => $s1, 'period' => '17 October 2026', 'starts' => '2026-10-17',
                'activity' => 'Projects Committee (Q2)', 'who' => 'Council Secretariat', 'cat' => 'governance'],
            ['semester' => $s1, 'period' => '18 and 25 October 2026', 'starts' => '2026-10-18', 'ends' => '2026-10-25',
                'activity' => 'Viva voce examinations', 'who' => 'Graduate Centre / Faculty Deans', 'cat' => 'examination'],
            ['semester' => $s1, 'period' => '19 – 23 October 2026', 'starts' => '2026-10-19', 'ends' => '2026-10-23',
                'activity' => 'MRU Health Week', 'who' => 'Counsellor', 'cat' => 'student'],
            ['semester' => $s1, 'period' => '20 October 2026', 'starts' => '2026-10-20',
                'activity' => 'Finance and Planning Committee; Bursaries Committee meeting',
                'who' => 'Council Secretariat / Academic Registrar', 'cat' => 'governance'],
            ['semester' => $s1, 'period' => '23 October 2026', 'starts' => '2026-10-23',
                'activity' => "Students' Affairs Committee (Q2)", 'who' => 'Council Secretariat', 'cat' => 'governance'],
            ['semester' => $s1, 'period' => '26 October 2026', 'starts' => '2026-10-26',
                'activity' => 'October Research Seminar', 'who' => 'Graduate Centre', 'cat' => 'research'],
            ['semester' => $s1, 'period' => '26 – 30 October 2026', 'starts' => '2026-10-26', 'ends' => '2026-10-30',
                'activity' => 'Second assignment week', 'who' => 'All lecturers', 'cat' => 'academic'],
            ['semester' => $s1, 'period' => '27 October 2026', 'starts' => '2026-10-27',
                'activity' => 'Viva voce examinations; Resource Mobilisation Committee (Q2); Faculty of Education Board meeting',
                'who' => 'Graduate Centre / Council Secretariat / Dean, FoE', 'cat' => 'examination'],
            ['semester' => $s1, 'period' => '28 October 2026', 'starts' => '2026-10-28',
                'activity' => 'Viva voce examinations; MRU hall and hostel meeting; Teaching and Learning Committee',
                'who' => 'Graduate Centre / Warden / Manager, Quality Assurance', 'cat' => 'examination'],

            // -------------------------------------------------- November 2026
            ['semester' => $s1, 'period' => '1 November 2026', 'starts' => '2026-11-01',
                'activity' => 'Participation in Masaza Cup finals', 'who' => 'Marketing Officer', 'cat' => 'outreach'],
            ['semester' => $s1, 'period' => '2 November 2026', 'starts' => '2026-11-02',
                'activity' => 'Short Courses Committee meeting; Buganda Institutions games',
                'who' => 'Short Courses Coordinator, FSSAH / Marketing Officer', 'cat' => 'student'],
            ['semester' => $s1, 'period' => '2 – 5 November 2026', 'starts' => '2026-11-02', 'ends' => '2026-11-05',
                'activity' => 'Career Guidance Week', 'who' => 'Dean of Students', 'cat' => 'student'],
            ['semester' => $s1, 'period' => '3 November 2026', 'starts' => '2026-11-03',
                'activity' => 'University Budget meeting', 'who' => 'University Bursar', 'cat' => 'governance'],
            ['semester' => $s1, 'period' => '4 November 2026', 'starts' => '2026-11-04',
                'activity' => 'Human Resources departmental meeting; Estate and Facilities Management',
                'who' => 'Manager, HR / DVC & Estates Officer', 'cat' => 'governance'],
            ['semester' => $s1, 'period' => '5 November 2026', 'starts' => '2026-11-05',
                'activity' => 'Auditors Committee meeting (09:00)', 'who' => 'University Auditor', 'cat' => 'governance'],
            ['semester' => $s1, 'period' => '6 November 2026', 'starts' => '2026-11-06',
                'activity' => "Deans' Forum", 'who' => 'DVC', 'cat' => 'governance'],
            ['semester' => $s1, 'period' => '7 November 2026', 'starts' => '2026-11-07',
                'activity' => 'End of career guidance and school visits', 'who' => 'Marketing Officer', 'cat' => 'outreach'],
            ['semester' => $s1, 'period' => '9 November 2026', 'starts' => '2026-11-09',
                'activity' => 'Student tutorship programme recruitment and training; Academic and Quality Assurance Committee (Council Q2)',
                'who' => 'Dean, FBM / Governing Council Secretariat', 'cat' => 'academic'],
            ['semester' => $s1, 'period' => '10 November 2026', 'starts' => '2026-11-10',
                'activity' => 'Business Committee of Council (Q2); Resource Mobilisation Committee (Council Q2)',
                'who' => 'Governing Council Secretariat', 'cat' => 'governance'],
            ['semester' => $s1, 'period' => '11 November 2026', 'starts' => '2026-11-11',
                'activity' => 'Internship and field-trip planning; Audit and Risk Management Committee (Council Q2)',
                'who' => 'Dean, FBM / Heads of Department / Governing Council Secretariat', 'cat' => 'academic'],
            ['semester' => $s1, 'period' => '12 November 2026', 'starts' => '2026-11-12',
                'activity' => "Staff appraisal by students (09:00); Students' Affairs Committee (Council Q2)",
                'who' => 'Quality Assurance Unit / Governing Council Secretariat', 'cat' => 'governance'],
            ['semester' => $s1, 'period' => '13 November 2026', 'starts' => '2026-11-13',
                'activity' => 'Graduate Board of Senate meeting; Finance and Planning Committee (Council Q2); 53rd Senate meeting; Faculty of Education community engagement activity',
                'who' => 'DVC / CGC / Deans / Academic Registrar / Governing Council Secretariat', 'cat' => 'governance'],
            ['semester' => $s1, 'period' => '14 November 2026', 'starts' => '2026-11-14',
                'activity' => 'Extended MANCO meeting', 'who' => 'Management', 'cat' => 'governance'],
            ['semester' => $s1, 'period' => '16 November 2026', 'starts' => '2026-11-16',
                'activity' => 'Appointments and Governance Committee (Council Q2)', 'who' => 'Governing Council Secretariat', 'cat' => 'governance'],
            ['semester' => $s1, 'period' => '16 – 29 November 2026', 'starts' => '2026-11-16', 'ends' => '2026-11-29',
                'activity' => 'Semester I regular examinations', 'who' => 'Academic Registrar / Examinations Office', 'cat' => 'examination', 'key' => true],
            ['semester' => $s1, 'period' => '17 November 2026', 'starts' => '2026-11-17',
                'activity' => 'Finance Committee meeting; Projects Committee (Council Q2)',
                'who' => 'DVC / University Bursar / Governing Council Secretariat', 'cat' => 'governance'],
            ['semester' => $s1, 'period' => '18 – 30 November 2026', 'starts' => '2026-11-18', 'ends' => '2026-11-30',
                'activity' => 'Graduate Centre final examinations', 'who' => 'Graduate Centre / Academic Registrar', 'cat' => 'examination'],
            ['semester' => $s1, 'period' => '18 November 2026', 'starts' => '2026-11-18',
                'activity' => 'Business Committee (Council Q2)', 'who' => 'Governing Council Secretariat', 'cat' => 'governance'],
            ['semester' => $s1, 'period' => '19 November 2026', 'starts' => '2026-11-19',
                'activity' => 'Procurement Committee meeting; Human Resources meeting', 'who' => 'Chairperson / HR Officer', 'cat' => 'governance'],
            ['semester' => $s1, 'period' => '20 November 2026', 'starts' => '2026-11-20',
                'activity' => 'Governing Council — 2nd Quarterly Meeting', 'who' => 'Governing Council Secretariat', 'cat' => 'governance'],
            ['semester' => $s1, 'period' => '24 – 25 November 2026', 'starts' => '2026-11-24', 'ends' => '2026-11-25',
                'activity' => 'Faculty of Education departmental meetings; Teaching and Learning Committee',
                'who' => 'Dean, FoE / Manager, Quality Assurance', 'cat' => 'academic'],
            ['semester' => $s1, 'period' => '25 November 2026', 'starts' => '2026-11-25',
                'activity' => 'Faculty Board meetings', 'who' => 'Deans & faculty members', 'cat' => 'academic'],
            ['semester' => $s1, 'period' => '29 November 2026', 'starts' => '2026-11-29',
                'activity' => 'End of Semester I, Academic Year 2026/2027', 'who' => 'University', 'cat' => 'academic', 'key' => true],
            ['semester' => $s1, 'period' => '30 November 2026', 'starts' => '2026-11-30',
                'activity' => 'November Research Seminar', 'who' => 'Graduate Centre', 'cat' => 'research'],
            ['semester' => $s1, 'period' => 'November 2026', 'starts' => '2026-11-01', 'ends' => '2026-11-30',
                'activity' => 'Guest lecturer series, competitions and hackathons', 'who' => 'FBM Events Committee / Heads of Department', 'cat' => 'academic'],

            // -------------------------------------------------- December 2026
            ['semester' => $s1, 'period' => '2 – 5 December 2026', 'starts' => '2026-12-02', 'ends' => '2026-12-05',
                'activity' => 'Faculty Board meetings', 'who' => 'Deans of Faculties', 'cat' => 'academic'],
            ['semester' => $s1, 'period' => '3 – 22 December 2026', 'starts' => '2026-12-03', 'ends' => '2026-12-22',
                'activity' => 'Faculty of Education December in-service session', 'who' => 'Dean, FoE / Manager, In-service', 'cat' => 'academic'],
            ['semester' => $s1, 'period' => '4 December 2026', 'starts' => '2026-12-04',
                'activity' => '14th Graduation Ceremony (provisional)', 'who' => 'University', 'cat' => 'graduation', 'key' => true],
            ['semester' => $s1, 'period' => '7 – 31 December 2026', 'starts' => '2026-12-07', 'ends' => '2026-12-31',
                'activity' => 'December in-service session', 'who' => 'FoE / Manager, In-service', 'cat' => 'academic'],
            ['semester' => $s1, 'period' => '8 – 31 December 2026', 'starts' => '2026-12-08', 'ends' => '2026-12-31',
                'activity' => 'MEMA in-service December session', 'who' => 'FoE / Graduate Centre', 'cat' => 'academic'],
            ['semester' => $s1, 'period' => '9 December 2026', 'starts' => '2026-12-09',
                'activity' => "Deans' Forum", 'who' => 'DVC / Deans', 'cat' => 'governance'],
            ['semester' => $s1, 'period' => '10 – 15 December 2026', 'starts' => '2026-12-10', 'ends' => '2026-12-15',
                'activity' => 'Christmas wishes to UACE candidates and stakeholders', 'who' => 'Marketing Office', 'cat' => 'outreach'],
            ['semester' => $s1, 'period' => '11 December 2026', 'starts' => '2026-12-11',
                'activity' => 'Professor Munakukaama Memorial Lecture', 'who' => 'Faculty of Education', 'cat' => 'academic'],
            ['semester' => $s1, 'period' => '18 December 2026', 'starts' => '2026-12-18',
                'activity' => 'Hostel exit coordination', 'who' => 'Hostel Warden', 'cat' => 'student'],
            ['semester' => $s1, 'period' => '20 December 2026', 'starts' => '2026-12-20',
                'activity' => 'Christmas Carols', 'who' => 'Marketing Officer', 'cat' => 'student'],
            ['semester' => $s1, 'period' => '22 – 27 December 2026', 'starts' => '2026-12-22', 'ends' => '2026-12-27',
                'activity' => 'University closed — festive season break', 'who' => 'All staff and students', 'cat' => 'holiday', 'key' => true],
            ['semester' => $s1, 'period' => '25 – 26 December 2026', 'starts' => '2026-12-25', 'ends' => '2026-12-26',
                'activity' => 'Public Holiday: Christmas Day and Boxing Day', 'who' => 'All staff and students to note', 'cat' => 'holiday'],
            ['semester' => $s1, 'period' => 'December 2026', 'starts' => '2026-12-01', 'ends' => '2026-12-31',
                'activity' => 'Faculty of Business and Management e-newsletter — first edition', 'who' => 'FBM Marketing', 'cat' => 'outreach'],

            // --------------------------------------------------- January 2027
            ['semester' => $s2, 'period' => '1 January 2027', 'starts' => '2027-01-01',
                'activity' => "Public Holiday: New Year's Day", 'who' => 'All staff and students to note', 'cat' => 'holiday'],
            ['semester' => $s2, 'period' => '2 – 31 January 2027', 'starts' => '2027-01-02', 'ends' => '2027-01-31',
                'activity' => 'MEMA in-service January session; applications for admission open',
                'who' => 'FoE / Manager, In-service / Graduate Centre', 'cat' => 'academic'],
            ['semester' => $s2, 'period' => '3 January 2027', 'starts' => '2027-01-03',
                'activity' => 'Study applications and admissions are ongoing', 'who' => 'Admissions Office', 'cat' => 'outreach', 'key' => true],
            ['semester' => $s2, 'period' => '4 January 2027', 'starts' => '2027-01-04',
                'activity' => '54th Senate meeting', 'who' => 'Academic Registrar', 'cat' => 'governance'],
            ['semester' => $s2, 'period' => '4 – 26 January 2027', 'starts' => '2027-01-04', 'ends' => '2027-01-26',
                'activity' => 'General January in-service session', 'who' => 'FoE / Manager, In-service', 'cat' => 'academic'],
            ['semester' => $s2, 'period' => '5 January 2027', 'starts' => '2027-01-05',
                'activity' => 'Opening of Semester II, Academic Year 2026/2027', 'who' => 'Staff & students', 'cat' => 'academic', 'key' => true],
            ['semester' => $s2, 'period' => '6 January 2027', 'starts' => '2027-01-06',
                'activity' => 'Bursaries Committee meeting', 'who' => "Academic Registrar / Bursar's Office", 'cat' => 'governance'],
            ['semester' => $s2, 'period' => '8 January 2027', 'starts' => '2027-01-08',
                'activity' => 'Academic and Quality Assurance Committee (Q3)', 'who' => 'Council Secretariat', 'cat' => 'governance'],
            ['semester' => $s2, 'period' => '11 January 2027', 'starts' => '2027-01-11',
                'activity' => 'Programmes and Finance Committee', 'who' => 'DVC / Academic Registrar / Deans / QA', 'cat' => 'governance'],
            ['semester' => $s2, 'period' => '12 January 2027', 'starts' => '2027-01-12',
                'activity' => 'Resource Mobilisation Committee (Q3); competence-based education workshop; Faculty Board meeting',
                'who' => 'Council Secretariat / Dean, FBM / Quality Assurance Unit', 'cat' => 'governance'],
            ['semester' => $s2, 'period' => '14 January 2027', 'starts' => '2027-01-14',
                'activity' => '36th Examinations Board meeting', 'who' => 'DVC / Examinations Coordinator', 'cat' => 'examination'],
            ['semester' => $s2, 'period' => '16 January 2027', 'starts' => '2027-01-16',
                'activity' => 'Faculty of Education student leadership training', 'who' => 'Faculty of Education', 'cat' => 'student'],
            ['semester' => $s2, 'period' => '16 – 26 January 2027', 'starts' => '2027-01-16', 'ends' => '2027-01-26',
                'activity' => 'Faculty of Education January in-service session', 'who' => 'Dean, FoE / Manager, In-service', 'cat' => 'academic'],
            ['semester' => $s2, 'period' => '19 January 2027', 'starts' => '2027-01-19',
                'activity' => 'Audit and Risk Management Committee (Q3); Faculty of Education departmental meeting',
                'who' => 'Council Secretariat / Dean, FoE', 'cat' => 'governance'],
            ['semester' => $s2, 'period' => '20 January – 10 February 2027', 'starts' => '2027-01-20', 'ends' => '2027-02-10',
                'activity' => 'Semester II sports friendlies; Estate and Facilities Management',
                'who' => 'Sports Tutor / DVC & Estates Officer', 'cat' => 'student'],
            ['semester' => $s2, 'period' => '21 January 2027', 'starts' => '2027-01-21',
                'activity' => 'Teaching and Learning Committee', 'who' => 'Manager, Quality Assurance', 'cat' => 'governance'],
            ['semester' => $s2, 'period' => '21 – 23 January 2027', 'starts' => '2027-01-21', 'ends' => '2027-01-23',
                'activity' => 'Training on competency-based education and training (CBET)', 'who' => 'Dean, Faculty of Education', 'cat' => 'academic'],
            ['semester' => $s2, 'period' => '22 January 2027', 'starts' => '2027-01-22',
                'activity' => "Students' Affairs Committee (Q3)", 'who' => 'Council Secretariat', 'cat' => 'governance'],
            ['semester' => $s2, 'period' => '25 January 2027', 'starts' => '2027-01-25',
                'activity' => 'Finance and Planning Committee (Q3)', 'who' => 'Council Secretariat', 'cat' => 'governance'],
            ['semester' => $s2, 'period' => '26 January 2027', 'starts' => '2027-01-26',
                'activity' => 'Faculty of Education Board meeting', 'who' => 'Dean, FoE / Faculty Board', 'cat' => 'academic'],
            ['semester' => $s2, 'period' => '29 January 2027', 'starts' => '2027-01-29',
                'activity' => 'Appointments and Governance Committee (Q3); Examinations Irregularities / Disciplinary Committee — Kakeeka',
                'who' => 'Council Secretariat / DVC / Examinations Coordinator', 'cat' => 'governance'],

            // -------------------------------------------------- February 2027
            ['semester' => $s2, 'period' => '2 February 2027', 'starts' => '2027-02-02',
                'activity' => 'Projects Committee (Q3)', 'who' => 'Council Secretariat', 'cat' => 'governance'],
            ['semester' => $s2, 'period' => '2 – 8 February 2027', 'starts' => '2027-02-02', 'ends' => '2027-02-08',
                'activity' => 'First assessment week', 'who' => 'All lecturers', 'cat' => 'examination', 'key' => true],
            ['semester' => $s2, 'period' => '5 February 2027', 'starts' => '2027-02-05',
                'activity' => 'Examinations Irregularities / Disciplinary Committee — Kirumba', 'who' => 'DVC / Examinations Coordinator', 'cat' => 'examination'],
            ['semester' => $s2, 'period' => '5 – 6 February 2027', 'starts' => '2027-02-05', 'ends' => '2027-02-06',
                'activity' => 'Dean of Students departmental workshop', 'who' => 'Dean of Students', 'cat' => 'student'],
            ['semester' => $s2, 'period' => '8 February 2027', 'starts' => '2027-02-08',
                'activity' => 'Academic and Quality Assurance Committee (Council Q3)', 'who' => 'Council Secretariat', 'cat' => 'governance'],
            ['semester' => $s2, 'period' => '9 February 2027', 'starts' => '2027-02-09',
                'activity' => 'Business Committee (Q3); Resource Mobilisation Committee (Council Q3)', 'who' => 'Council Secretariat', 'cat' => 'governance'],
            ['semester' => $s2, 'period' => '10 February – 18 March 2027', 'starts' => '2027-02-10', 'ends' => '2027-03-18',
                'activity' => 'Student research proposal defence', 'who' => 'Heads of Department / Research Coordinator', 'cat' => 'research'],
            ['semester' => $s2, 'period' => '10 February 2027', 'starts' => '2027-02-10',
                'activity' => 'Audit and Risk Management Committee (Council Q3)', 'who' => 'Governing Council Secretariat', 'cat' => 'governance'],
            ['semester' => $s2, 'period' => '11 February 2027', 'starts' => '2027-02-11',
                'activity' => "Students' Affairs Committee (Council Q3)", 'who' => 'Governing Council Secretariat', 'cat' => 'governance'],
            ['semester' => $s2, 'period' => '12 February 2027', 'starts' => '2027-02-12',
                'activity' => 'Finance and Planning Committee (Council Q3)', 'who' => 'Governing Council Secretariat', 'cat' => 'governance'],
            ['semester' => $s2, 'period' => '13 February 2027', 'starts' => '2027-02-13',
                'activity' => 'Commencement of Weekend Graduate Centre Semester II', 'who' => 'CGC / Faculty Deans', 'cat' => 'academic'],
            ['semester' => $s2, 'period' => '15 February 2027', 'starts' => '2027-02-15',
                'activity' => 'Appointments and Governance Committee (Council Q3)', 'who' => 'Governing Council Secretariat', 'cat' => 'governance'],
            ['semester' => $s2, 'period' => '16 February 2027', 'starts' => '2027-02-16',
                'activity' => 'Archbishop Janani Luwum Day; Projects Committee (Council Q3)',
                'who' => 'All staff & students to note / Governing Council Secretariat', 'cat' => 'holiday'],
            ['semester' => $s2, 'period' => '17 February 2027', 'starts' => '2027-02-17',
                'activity' => 'Business Committee (Council Q3)', 'who' => 'Governing Council Secretariat', 'cat' => 'governance'],
            ['semester' => $s2, 'period' => '18 February 2027', 'starts' => '2027-02-18',
                'activity' => '55th Senate meeting', 'who' => 'Academic Registrar', 'cat' => 'governance'],
            ['semester' => $s2, 'period' => '19 February 2027', 'starts' => '2027-02-19',
                'activity' => 'Graduate academic writing session; Governing Council — 3rd Quarterly Meeting',
                'who' => 'Graduate Centre / Council Secretariat', 'cat' => 'governance'],
            ['semester' => $s2, 'period' => '20 February 2027', 'starts' => '2027-02-20',
                'activity' => 'Faculty of Education research publication training', 'who' => 'Dean, FoE / Research Committee', 'cat' => 'research'],
            ['semester' => $s2, 'period' => '22 February 2027', 'starts' => '2027-02-22',
                'activity' => 'February Research Seminar', 'who' => 'Graduate Centre', 'cat' => 'research'],
            ['semester' => $s2, 'period' => '23 – 24 February 2027', 'starts' => '2027-02-23', 'ends' => '2027-02-24',
                'activity' => 'Guild General Assembly', 'who' => 'Guild Government', 'cat' => 'student'],
            ['semester' => $s2, 'period' => '24 February 2027', 'starts' => '2027-02-24',
                'activity' => 'Extended MANCO meeting', 'who' => 'Management', 'cat' => 'governance'],
            ['semester' => $s2, 'period' => 'February 2027', 'starts' => '2027-02-01', 'ends' => '2027-02-28',
                'activity' => 'Guest lecturer series, competitions and hackathons', 'who' => 'FBM Events Committee / Heads of Department', 'cat' => 'academic'],

            // ----------------------------------------------------- March 2027
            ['semester' => $s2, 'period' => '2 March 2027', 'starts' => '2027-03-02',
                'activity' => "Student Leaders' Symposium; Estate and Facilities Management; Faculty Board meeting — FSSAH",
                'who' => 'Dean of Students / DVC & Estates Officer / Dean & faculty staff', 'cat' => 'student'],
            ['semester' => $s2, 'period' => '5 March 2027', 'starts' => '2027-03-05',
                'activity' => "Deans' Forum", 'who' => 'DVC', 'cat' => 'governance'],
            ['semester' => $s2, 'period' => '6 March 2027', 'starts' => '2027-03-06',
                'activity' => 'Last day for setting Semester II examination papers and marking schemes', 'who' => 'All academic staff', 'cat' => 'examination'],
            ['semester' => $s2, 'period' => '8 March 2027', 'starts' => '2027-03-08',
                'activity' => "Public Holiday: International Women's Day", 'who' => 'All staff and students to note', 'cat' => 'holiday'],
            ['semester' => $s2, 'period' => '11 March 2027', 'starts' => '2027-03-11',
                'activity' => 'Student community outreach; Procurement Committee meeting', 'who' => 'Dean of Students / Dr P. Bwowe', 'cat' => 'outreach'],
            ['semester' => $s2, 'period' => '12 March 2027', 'starts' => '2027-03-12',
                'activity' => '56th Senate meeting', 'who' => 'Academic Registrar', 'cat' => 'governance'],
            ['semester' => $s2, 'period' => '13 March 2027', 'starts' => '2027-03-13',
                'activity' => 'Display of Semester II examination timetable; Faculty of Education community engagement activity',
                'who' => 'Deans / Heads of Department / Dean, FoE', 'cat' => 'examination', 'key' => true],
            ['semester' => $s2, 'period' => '16 March 2027', 'starts' => '2027-03-16',
                'activity' => 'Grants, Projects and Innovations Committee; Faculty of Education departmental meeting',
                'who' => 'Graduate Centre / Dean, FoE', 'cat' => 'governance'],
            ['semester' => $s2, 'period' => '17 – 21 March 2027', 'starts' => '2027-03-17', 'ends' => '2027-03-21',
                'activity' => 'Moderation of examinations', 'who' => 'Deans / Heads of Department', 'cat' => 'examination'],
            ['semester' => $s2, 'period' => '18 March 2027', 'starts' => '2027-03-18',
                'activity' => 'Teaching and Learning Committee; Guild Representative Council sitting',
                'who' => 'Manager, Quality Assurance / Dean of Students', 'cat' => 'governance'],
            ['semester' => $s2, 'period' => '19 March 2027', 'starts' => '2027-03-19',
                'activity' => 'Community engagement and outreach', 'who' => 'Coordinator — Assoc. Prof. Nakijoba', 'cat' => 'outreach'],
            ['semester' => $s2, 'period' => '20 March 2027', 'starts' => '2027-03-20',
                'activity' => 'Public Holiday: Eid al-Fitr (subject to moon sighting)', 'who' => 'All staff and students to note', 'cat' => 'holiday'],
            ['semester' => $s2, 'period' => '23 – 29 March 2027', 'starts' => '2027-03-23', 'ends' => '2027-03-29',
                'activity' => 'Second assessment week', 'who' => 'All lecturers', 'cat' => 'examination'],
            ['semester' => $s2, 'period' => '29 March 2027', 'starts' => '2027-03-29',
                'activity' => 'March Research Seminar', 'who' => 'Graduate Centre', 'cat' => 'research'],
            ['semester' => $s2, 'period' => '30 March 2027', 'starts' => '2027-03-30',
                'activity' => 'Faculty of Education Board meeting; Auditors Committee meeting (internal)',
                'who' => 'Dean, FoE / Auditors', 'cat' => 'governance'],
            ['semester' => $s2, 'period' => 'March 2027', 'starts' => '2027-03-01', 'ends' => '2027-03-31',
                'activity' => 'Research training workshop on publication and academic writing', 'who' => 'FBM Research and Innovation Committee', 'cat' => 'research'],
            ['semester' => $s2, 'period' => 'March 2027', 'starts' => '2027-03-01', 'ends' => '2027-03-31',
                'activity' => 'NCHE exhibition (location pending); phone calls to students and parents in vacation (phase 1)',
                'who' => 'Marketing Officer', 'cat' => 'outreach'],

            // ----------------------------------------------------- April 2027
            ['semester' => $s2, 'period' => '3 April 2027', 'starts' => '2027-04-03',
                'activity' => 'Public Holiday: Good Friday — date pending confirmation', 'who' => 'Staff & students to note', 'cat' => 'holiday'],
            ['semester' => $s2, 'period' => '5 April 2027', 'starts' => '2027-04-05',
                'activity' => 'Public Holiday: Easter Sunday — date pending confirmation', 'who' => 'Staff & students to note', 'cat' => 'holiday'],
            ['semester' => $s2, 'period' => '6 April 2027', 'starts' => '2027-04-06',
                'activity' => 'Public Holiday: Easter Monday — date pending confirmation', 'who' => 'Staff & students to note', 'cat' => 'holiday'],
            ['semester' => $s2, 'period' => '8 April 2027', 'starts' => '2027-04-08',
                'activity' => 'FSSAH Faculty Board meeting', 'who' => 'Dean & faculty staff', 'cat' => 'academic'],
            ['semester' => $s2, 'period' => '13 – 26 April 2027', 'starts' => '2027-04-13', 'ends' => '2027-04-26',
                'activity' => 'Semester II regular examinations', 'who' => 'Academic Registrar / Examinations Office', 'cat' => 'examination', 'key' => true],
            ['semester' => $s2, 'period' => '15 – 20 April 2027', 'starts' => '2027-04-15', 'ends' => '2027-04-20',
                'activity' => '2027/2028 meeting with MRU agents and partners; visit to Masaza and Gombolola chiefs',
                'who' => 'Marketing Officer', 'cat' => 'outreach'],
            ['semester' => $s2, 'period' => '15 April 2027', 'starts' => '2027-04-15',
                'activity' => 'Entrepreneurship workshop and boot camp; visiting schools', 'who' => 'FBM Heads of Department / FSTEAD', 'cat' => 'outreach'],
            ['semester' => $s2, 'period' => '17 April 2027', 'starts' => '2027-04-17',
                'activity' => 'Faculty of Education CBET training', 'who' => 'Dean, FoE / Quality Assurance Unit', 'cat' => 'academic'],
            ['semester' => $s2, 'period' => '23 April 2027', 'starts' => '2027-04-23',
                'activity' => 'Guild elections', 'who' => 'Dean of Students', 'cat' => 'student', 'key' => true],
            ['semester' => $s2, 'period' => '24 April 2027', 'starts' => '2027-04-24',
                'activity' => 'Faculty of Education community engagement activity', 'who' => 'Dean, FoE / Heads of Department', 'cat' => 'outreach'],
            ['semester' => $s2, 'period' => '26 April 2027', 'starts' => '2027-04-26',
                'activity' => 'End of Semester II, Academic Year 2026/2027; April Research Seminar',
                'who' => 'Academic Registrar / Graduate Centre', 'cat' => 'academic', 'key' => true],
            ['semester' => $s2, 'period' => '27 April 2027', 'starts' => '2027-04-27',
                'activity' => 'Extended MANCO meeting', 'who' => 'Management', 'cat' => 'governance'],
            ['semester' => $s2, 'period' => '30 April 2027', 'starts' => '2027-04-30',
                'activity' => "Guild handover and swearing-in ceremony; Deans' Forum", 'who' => 'Dean of Students / DVC', 'cat' => 'student'],
            ['semester' => $s2, 'period' => 'April 2027', 'starts' => '2027-04-01', 'ends' => '2027-04-30',
                'activity' => 'External branding through education fairs and exhibitions; water, sanitation and hygiene (WASH) initiatives',
                'who' => 'FBM Marketing / FBM CSR Committee', 'cat' => 'outreach'],
            ['semester' => $s2, 'period' => 'April – September 2027', 'starts' => '2027-04-01', 'ends' => '2027-09-30',
                'activity' => 'Kabaka Birthday Run; television and radio advertisements', 'who' => 'Marketing Officer', 'cat' => 'outreach'],

            // ------------------------------------------------------- May 2027
            ['semester' => $s2, 'period' => '1 May 2027', 'starts' => '2027-05-01',
                'activity' => 'Public Holiday: Labour Day', 'who' => 'Staff & students to note', 'cat' => 'holiday'],
            ['semester' => $s2, 'period' => '4 – 28 May 2027', 'starts' => '2027-05-04', 'ends' => '2027-05-28',
                'activity' => 'May in-service session', 'who' => 'FoE / Graduate Centre', 'cat' => 'academic'],
            ['semester' => $s2, 'period' => '5 May 2027', 'starts' => '2027-05-05',
                'activity' => '57th Senate meeting', 'who' => 'Academic Registrar', 'cat' => 'governance'],
            ['semester' => $s2, 'period' => '10 – 27 May 2027', 'starts' => '2027-05-10', 'ends' => '2027-05-27',
                'activity' => 'Faculty of Education May in-service session', 'who' => 'Dean, FoE / Manager, In-service', 'cat' => 'academic'],
            ['semester' => $s2, 'period' => '10 May 2027', 'starts' => '2027-05-10',
                'activity' => 'Academic and Quality Assurance Committee (Council Q4)', 'who' => 'Governing Council Secretariat', 'cat' => 'governance'],
            ['semester' => $s2, 'period' => '11 May 2027', 'starts' => '2027-05-11',
                'activity' => 'Resource Mobilisation Committee (Council Q4)', 'who' => 'Governing Council Secretariat', 'cat' => 'governance'],
            ['semester' => $s2, 'period' => '12 May 2027', 'starts' => '2027-05-12',
                'activity' => 'Audit and Risk Management Committee (Council Q4)', 'who' => 'Governing Council Secretariat', 'cat' => 'governance'],
            ['semester' => $s2, 'period' => '13 May 2027', 'starts' => '2027-05-13',
                'activity' => "Students' Affairs Committee (Council Q4)", 'who' => 'Governing Council Secretariat', 'cat' => 'governance'],
            ['semester' => $s2, 'period' => '14 May 2027', 'starts' => '2027-05-14',
                'activity' => 'Finance and Planning Committee (Council Q4)', 'who' => 'Governing Council Secretariat', 'cat' => 'governance'],
            ['semester' => $s2, 'period' => '16 – 17 May 2027', 'starts' => '2027-05-16', 'ends' => '2027-05-17',
                'activity' => 'Summer School commencement and registration — closing date to be confirmed', 'who' => 'Deans / HoDs / Lecturers', 'cat' => 'academic'],
            ['semester' => $s2, 'period' => '17 – 31 May 2027', 'starts' => '2027-05-17', 'ends' => '2027-05-31',
                'activity' => 'End-of-Semester II Graduate Centre examinations', 'who' => 'Graduate Centre / Examinations Coordinator', 'cat' => 'examination'],
            ['semester' => $s2, 'period' => '17 May 2027', 'starts' => '2027-05-17',
                'activity' => 'Appointments and Governance Committee (Council Q4)', 'who' => 'Governing Council Secretariat', 'cat' => 'governance'],
            ['semester' => $s2, 'period' => '18 May 2027', 'starts' => '2027-05-18',
                'activity' => 'Faculty of Education departmental meeting; Projects Committee (Council Q4)',
                'who' => 'Dean, FoE / Governing Council Secretariat', 'cat' => 'governance'],
            ['semester' => $s2, 'period' => '19 – 23 May 2027', 'starts' => '2027-05-19', 'ends' => '2027-05-23',
                'activity' => 'Faculty Board meetings', 'who' => 'Deans of Faculties', 'cat' => 'academic'],
            ['semester' => $s2, 'period' => '19 May 2027', 'starts' => '2027-05-19',
                'activity' => 'Business Committee (Council Q4); student internship briefing',
                'who' => 'Governing Council Secretariat / Dean, FSSAH', 'cat' => 'governance'],
            ['semester' => $s2, 'period' => '21 and 28 May 2027', 'starts' => '2027-05-21', 'ends' => '2027-05-28',
                'activity' => 'Defence of graduate research proposals', 'who' => 'CGC / Faculty Deans', 'cat' => 'research'],
            ['semester' => $s2, 'period' => '21 May 2027', 'starts' => '2027-05-21',
                'activity' => 'Governing Council — 4th Quarterly Meeting (end of year)', 'who' => 'Governing Council Secretariat', 'cat' => 'governance'],
            ['semester' => $s2, 'period' => '23 – 24 May 2027', 'starts' => '2027-05-23', 'ends' => '2027-05-24',
                'activity' => 'Internship briefing — Faculty of Business and Management', 'who' => 'Dean / Heads of Department', 'cat' => 'academic'],
            ['semester' => $s2, 'period' => '27 May 2027', 'starts' => '2027-05-27',
                'activity' => 'Eid al-Adha', 'who' => 'Staff & students to note', 'cat' => 'holiday'],
            ['semester' => $s2, 'period' => '28 May 2027', 'starts' => '2027-05-28',
                'activity' => 'Teaching and Learning Committee', 'who' => 'Manager, Quality Assurance', 'cat' => 'governance'],
            ['semester' => $s2, 'period' => '29 May 2027', 'starts' => '2027-05-29',
                'activity' => 'Graduate academic writing session', 'who' => 'Graduate Centre', 'cat' => 'research'],
            ['semester' => $s2, 'period' => '31 May 2027', 'starts' => '2027-05-31',
                'activity' => 'May Research Seminar; FBM e-newsletter — second edition', 'who' => 'Graduate Centre / FBM Marketing', 'cat' => 'research'],
            ['semester' => $s2, 'period' => 'May 2027', 'starts' => '2027-05-01', 'ends' => '2027-05-31',
                'activity' => 'Phone calls to students and parents in vacation (phase 2)', 'who' => 'Marketing Office', 'cat' => 'outreach'],

            // ------------------------------------------------------ June 2027
            ['semester' => $rec, 'period' => '1 June – 31 July 2027', 'starts' => '2027-06-01', 'ends' => '2027-07-31',
                'activity' => 'Commencement of student internship and school practice', 'who' => 'Deans of Faculties', 'cat' => 'academic', 'key' => true],
            ['semester' => $rec, 'period' => '3 June 2027', 'starts' => '2027-06-03',
                'activity' => "Public Holiday: Martyrs' Day", 'who' => 'Staff & students to note', 'cat' => 'holiday'],
            ['semester' => $rec, 'period' => '8 June 2027', 'starts' => '2027-06-08',
                'activity' => 'Commencement of Summer School sessions', 'who' => 'Academic Registrar & Deans', 'cat' => 'academic'],
            ['semester' => $rec, 'period' => '9 June 2027', 'starts' => '2027-06-09',
                'activity' => 'Public Holiday: National Heroes Day', 'who' => 'Staff & students to note', 'cat' => 'holiday'],
            ['semester' => $rec, 'period' => '10 June 2027', 'starts' => '2027-06-10',
                'activity' => 'Examinations Board meeting — meeting number to be confirmed', 'who' => 'Deans / DVC / Academic Registrar / QA', 'cat' => 'examination'],
            ['semester' => $rec, 'period' => '10 – 12 June 2027', 'starts' => '2027-06-10', 'ends' => '2027-06-12',
                'activity' => 'Faculty of Education inter-campus sports competitions', 'who' => 'Faculty of Education / Sports Office', 'cat' => 'student'],
            ['semester' => $rec, 'period' => '15 June 2027', 'starts' => '2027-06-15',
                'activity' => 'Extended MANCO meeting', 'who' => 'Management', 'cat' => 'governance'],
            ['semester' => $rec, 'period' => '16 June 2027', 'starts' => '2027-06-16',
                'activity' => "Deans' Forum", 'who' => 'DVC', 'cat' => 'governance'],
            ['semester' => $rec, 'period' => '17 June 2027', 'starts' => '2027-06-17',
                'activity' => 'Examinations Irregularities / Disciplinary Committee — Kirumba; Research, Ethics, Publications and Quality Assurance Committee',
                'who' => 'DVC / Examinations Coordinator / Graduate Centre', 'cat' => 'examination'],
            ['semester' => $rec, 'period' => '18 June 2027', 'starts' => '2027-06-18',
                'activity' => 'Examinations Irregularities / Disciplinary Committee — Kakeeka', 'who' => 'DVC / Examinations Coordinator', 'cat' => 'examination'],
            ['semester' => $rec, 'period' => '19 June 2027', 'starts' => '2027-06-19',
                'activity' => 'Procurement Committee meeting (09:00)', 'who' => 'Dr P. Bwowe', 'cat' => 'governance'],
            ['semester' => $rec, 'period' => '23 June 2027', 'starts' => '2027-06-23',
                'activity' => '58th Senate meeting', 'who' => 'Academic Registrar', 'cat' => 'governance'],
            ['semester' => $rec, 'period' => '28 June 2027', 'starts' => '2027-06-28',
                'activity' => 'June Research Seminar', 'who' => 'Graduate Centre', 'cat' => 'research'],
            ['semester' => $rec, 'period' => '29 June 2027', 'starts' => '2027-06-29',
                'activity' => 'Estate and Facilities Management', 'who' => 'DVC & Estates Officer', 'cat' => 'governance'],
            ['semester' => $rec, 'period' => 'June 2027', 'starts' => '2027-06-01', 'ends' => '2027-06-30',
                'activity' => 'Annual NCHE exhibition preparation and participation; review of brochures, prospectus and flyers; CBS PEWOSA trade fair',
                'who' => 'FBM Marketing Committee / Marketing Officer', 'cat' => 'outreach'],

            // ------------------------------------------------------ July 2027
            ['semester' => $rec, 'period' => '1 July 2027', 'starts' => '2027-07-01',
                'activity' => 'Commencement of community outreach activities', 'who' => 'Co-ordinator, Graduate School', 'cat' => 'outreach'],
            ['semester' => $rec, 'period' => '5 July 2027', 'starts' => '2027-07-05',
                'activity' => 'Grants, Projects and Innovations Committee', 'who' => 'Graduate Centre', 'cat' => 'governance'],
            ['semester' => $rec, 'period' => '26 July 2027', 'starts' => '2027-07-26',
                'activity' => 'July Research Seminar', 'who' => 'Graduate Centre', 'cat' => 'research'],
            ['semester' => $rec, 'period' => '31 July 2027', 'starts' => '2027-07-31',
                'activity' => 'End of internship and school practice', 'who' => 'Deans of Faculties', 'cat' => 'academic', 'key' => true],
            ['semester' => $rec, 'period' => 'July 2027', 'starts' => '2027-07-01', 'ends' => '2027-07-31',
                'activity' => 'Phone calls to students and parents in vacation (phase 3)', 'who' => 'Marketing Office', 'cat' => 'outreach'],
            ['semester' => $rec, 'period' => '31 August 2027', 'starts' => '2027-08-31',
                'activity' => 'Submission of Graduate School thesis (advance date beyond the almanac)', 'who' => 'Graduate Centre', 'cat' => 'research'],

            // -------------------------------------- Ongoing / cross-year work
            ['semester' => $on, 'period' => 'February – July 2027',
                'activity' => 'Marketing Committee meeting every Thursday; community outreach in Central, Eastern and Western districts — admitting for the August intake and sensitising about the government loan',
                'who' => 'Marketing Department', 'cat' => 'outreach'],
            ['semester' => $on, 'period' => 'August – October 2026',
                'activity' => 'Grant initiation and applications', 'who' => 'Dean, FBM / Heads of Department', 'cat' => 'research'],
            ['semester' => $on, 'period' => 'January – February 2027',
                'activity' => 'Publication planning', 'who' => 'All FBM academic staff / Research Committee', 'cat' => 'research'],
            ['semester' => $on, 'period' => 'February – May 2027',
                'activity' => 'Faculty exchange programmes and international fairs', 'who' => 'Dean, FBM / International Office', 'cat' => 'outreach'],
            ['semester' => $on, 'period' => 'April – May 2027',
                'activity' => 'Academic staff article-publication or conference-presentation milestone',
                'who' => 'All FBM academic staff / Research Committee', 'cat' => 'research'],
            ['semester' => $on, 'period' => 'May – July 2027',
                'activity' => 'Faculty alumni chapter activation', 'who' => 'Dean, FBM', 'cat' => 'student'],
            ['semester' => $on, 'period' => 'Throughout the year',
                'activity' => 'Short learning programme: SACCO governance and leadership', 'who' => 'Dean, FBM', 'cat' => 'academic'],
            ['semester' => $on, 'period' => 'Throughout the year',
                'activity' => 'Short learning programme for Senior Six leavers and unemployed youth: job-entry and job-creation skills',
                'who' => 'FBM Career Guidance / Dean, FBM', 'cat' => 'academic'],
            ['semester' => $on, 'period' => 'Throughout the year',
                'activity' => 'Ethics training for government and non-government personnel', 'who' => 'Dean, FBM', 'cat' => 'academic'],
            ['semester' => $on, 'period' => 'Throughout the year',
                'activity' => 'EFRIS training', 'who' => 'Dean, FBM', 'cat' => 'academic'],
            ['semester' => $on, 'period' => 'Throughout the year',
                'activity' => 'Career guidance and faculty webpage updates', 'who' => 'FBM Internal Marketing', 'cat' => 'outreach'],
            ['semester' => $on, 'period' => 'Throughout the year',
                'activity' => 'Research-focused partnerships, collaborations and MoUs', 'who' => 'Dean, FBM / Heads of Department', 'cat' => 'research'],
            ['semester' => $on, 'period' => 'Throughout the year',
                'activity' => 'Community engagement partnerships and corporate social responsibility', 'who' => 'Dean, FBM', 'cat' => 'outreach'],
            ['semester' => $on, 'period' => 'Throughout the year',
                'activity' => 'Stakeholder engagement', 'who' => 'Dean, FBM', 'cat' => 'outreach'],
            ['semester' => $on, 'period' => 'Throughout the year',
                'activity' => 'Digital and video marketing', 'who' => 'FBM Marketing', 'cat' => 'outreach'],
            ['semester' => $on, 'period' => 'Across the academic year',
                'activity' => 'Business clinics supporting local enterprises', 'who' => 'FBM Business and Entrepreneurship Unit', 'cat' => 'outreach'],
            ['semester' => $on, 'period' => 'Date to be confirmed',
                'activity' => 'Community outreach activity', 'who' => 'Dean of Students', 'cat' => 'outreach'],
            ['semester' => $on, 'period' => 'Date to be confirmed',
                'activity' => 'East African University Games; awards for outstanding student athletes', 'who' => 'Dean of Students / Sports Tutor', 'cat' => 'student'],
            ['semester' => $on, 'period' => 'Date to be confirmed',
                'activity' => "Women's Day celebration", 'who' => 'Dean of Students', 'cat' => 'student'],
            ['semester' => $on, 'period' => 'Date to be confirmed',
                'activity' => 'Guild campaigns, presidential debate and induction of incoming Guild leaders',
                'who' => 'Dean of Students / Guild Electoral Commission', 'cat' => 'student'],
            ['semester' => $on, 'period' => 'Date to be confirmed',
                'activity' => 'Miss and Mr MRU', 'who' => 'Dean of Students', 'cat' => 'student'],
            ['semester' => $on, 'period' => 'Date to be confirmed',
                'activity' => 'Alumni Executive Committee meeting; Student Affairs Committee meeting', 'who' => 'Dean of Students', 'cat' => 'student'],
        ];
    }
}
